### ISSUE TITLE
Extract Twitter Stream by UserId or by Keywoard

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/wheretolive-backend#1]
Library to use
1. [Twitter4J](http://twitter4j.org/en/index.html)
2. [Akka Stream]() or [Spark Streaming]()

Examples
- [twitter client example in scala](http://alvinalexander.com/scala/scala-twitter-client-twitter-api-example), [Akka Spray](http://www.cakesolutions.net/teamblogs/2013/12/08/streaming-twitter-api-in-akka-and-spray)

**Comment by Gigitsu** [comment]
[Here is a good example on how to use twitter4j stream api with scala](https://bcomposes.wordpress.com/2013/02/09/using-twitter4j-with-scala-to-access-streaming-tweets/)

**Comment by fabiofumarola** [comment]
Pipeline for each Tweet:

Stateless Transformation: basic information extraction
1. filter tweet with url
2. for each tweet extract the html from the given url
3. nlp pipeline (named entities)
4. save the data into elasticsearch

Stateful Transformation: Event Detection and Storyline tracking
1a. for the tweets with url we extract the html 
1b. for the other tweets nothing
2. nlp for each tweet
3. event detection
4. save data

**Comment by fabiofumarola** [comment]
Invalid basing on issue #47
