### ISSUE TITLE
Issue in elasticsearch cluster on azure

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/wheretolive-backend#44]
I want to understand why nodes go down.
I found some interesting discussions
1. [Possible causes for 'transport disconnected' errors in node discovery?](https://groups.google.com/forum/#!topic/elasticsearch/ULE3eXWepzk)
2. [multi data-center nodes going yellow](https://groups.google.com/forum/#!msg/elasticsearch/c9JmaiVfBb0/9XZM6ZJpoBwJ)

Thus, the problem can be related to the facts that:
1. the nodes are not used and so the tcp connection is closed by azure
2. the keep_alive time of tcp socket is too high

**Comment by fabiofumarola** [comment]
Now I have changed to 

```

net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 20
```

in /etc/sysctl.conf

**Comment by Gigitsu** [comment]
Can we close this issue?
